sudo: false
language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
script:
  - export RAILS_ENV=test
  - bundle exec rake app:db:create app:db:migrate
  - bundle exec rspec spec && bundle exec codeclimate-test-reporter
env:
  - THREADSAFE=true DB=mysql
  - THREADSAFE=false DB=mysql
  - THREADSAFE=true DB=sqlite
  - THREADSAFE=false DB=sqlite
  - THREADSAFE=true DB=postgresql
  - THREADSAFE=false DB=postgresql
gemfile:
  - gemfiles/Gemfile.rails-5.0-stable
  - gemfiles/Gemfile.rails-4.2-stable
  - gemfiles/Gemfile.rails-4.1-stable
  - gemfiles/Gemfile.rails-4.0-stable
  - gemfiles/Gemfile.rails-3.2-stable
  - Gemfile
matrix:
  allow_failures:
    - rvm: 2.0.0 # Allowed to fail in favor of supporting Rails 5 which requires Ruby 2.2
    - rvm: 2.1.0
notifications:
    hipchat:
        rooms:
            - secure: "cVvKnySyhAuBtAqXKwxsMamfjkGe63OldAdP4eSNv6syr0BNcJirfDN6OsH1bzAbvCq/lEK1udLDzPrEsP0S51zBG2tGaeY7pXeBhHigBGFmC6wsAfMtPkDTyursm6f6Orl0LrMB4RPTNi6RFXdKDvTk430NBjh8YgKkZ7EzBtg="
addons:
    code_climate:
        repo_token: c209fccefc8ce2e54a4ba49867ab7762023ba326a836616eb36afe8016bd56bf
